on:
  push:
    tags:
      - "adaptit-*"
#    branches:
#      - release

jobs:
  build-dpkg:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: focal
            uses: kanaka/build-dpkg@focal-v1
          - distro: bionic
            uses: kanaka/build-dpkg@bionic-v1
    steps:
      - uses: actions/checkout@v2

      - name: autogen.sh
        run: |
          echo "Running autogen.sh in bin/linux"
          cd bin/linux && ./autogen.sh

      - uses: ${{ matrix.uses }}
        id: build
        with:
          LOCAL: ${{ matrix.distro }}
          args: --unsigned-source --unsigned-changes

      - name: debug-show-files
        run: |
          echo "Files named *.changes"
          pwd
          find . | grep "\.changes" || true
          find artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ChangeLog
            artifacts/adaptit_*
            artifacts/adaptit-*
