on:
  push:
    tags:
      - "adaptit-*"
#    branches:
#      - release

jobs:
  build-dpkg:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {distro_short: 'focal',  distro_full: 'ubuntu:focal'}
          - {distro_short: 'bionic', distro_full: 'ubuntu:bionic'}
    steps:
      - uses: actions/checkout@v2

      - name: build-docker-build-dpkg
        run: docker build --build-arg DISTRO=${{ matrix.distro_full }} -t build-dpkg:${{ matrix.distro_short }} build-dpkg

#      - name: autogen.sh
#        run: |
#          echo "Running autogen.sh in bin/linux"
#          cd bin/linux && ./autogen.sh
#
#      - id: build-dpkg
#        uses: kanaka/build-dpkg@multi-v1
#        with:
#          LOCAL: ${{ matrix.distro_short }}
#          args: --unsigned-source --unsigned-changes
#          build-args: DISTRO=${{ matrix.distro_full }}

      - name: autogen.sh
        run: |
          echo "Running autogen.sh in bin/linux"
          docker run --rm -v $(pwd):/github/workspace --workdir /github/workspace/bin/linux build-dpkg:${{ matrix.distro_short }} ./autogen.sh

      - name: build-dkpg
        run: |
          echo "Doing package build"
          docker run --rm -v $(pwd):/github/workspace --workdir /github/workspace -e LOCAL=${{ matrix.distro_short }} build-dpkg:${{ matrix.distro_short }} /build.sh -I .git -I win32_utils --unsigned-source --unsigned-changes

      - name: debug-show-files
        run: |
          echo "Files named *.changes"
          pwd
          find . | grep "\.changes" || true
          find artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ChangeLog
            artifacts/adaptit_*
            artifacts/adaptit-*
