on:
  push:
    tags:
      - "adaptit-*"
#    branches:
#      - release

jobs:
  build-dpkg:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {distro_short: 'trusty', distro_full: 'ubuntu:trusty'}  # 14.04 LTS
          - {distro_short: 'xenial', distro_full: 'ubuntu:xenial'}  # 16.04 LTS
          #- {distro_short: 'bionic', distro_full: 'ubuntu:bionic'}  # 18.04 LTS
          - {distro_short: 'eoan',   distro_full: 'ubuntu:eoan'}    # 19.10
          #- {distro_short: 'focal',  distro_full: 'ubuntu:focal'}   # 20.04 LTS
          #- {distro_short: 'impish', distro_full: 'ubuntu:impish'}  # 21.10
          - {distro_short: 'sid',    distro_full: 'debian:sid'}
    steps:
      - uses: actions/checkout@v2
        with: {path: adaptit}

      - name: build-docker-build-dpkg
        run: docker build --build-arg DISTRO=${{ matrix.distro_full }} -t build-dpkg:${{ matrix.distro_short }} adaptit/build-dpkg

#      - name: autogen.sh
#        run: |
#          echo "Running autogen.sh in bin/linux"
#          cd bin/linux && ./autogen.sh
#
#      - id: build-dpkg
#        uses: kanaka/build-dpkg@multi-v1
#        with:
#          LOCAL: ${{ matrix.distro_short }}
#          args: --unsigned-source --unsigned-changes
#          build-args: DISTRO=${{ matrix.distro_full }}

      - name: autogen.sh
        run: |
          echo "Running autogen.sh in bin/linux"
          docker run --rm -v $(pwd):/github/workspace --workdir /github/workspace/adaptit/bin/linux build-dpkg:${{ matrix.distro_short }} ./autogen.sh

      - name: build-dkpg
        run: |
          echo "Doing package build"
          docker run --rm -v $(pwd):/github/workspace --workdir /github/workspace/adaptit -e LOCAL=${{ matrix.distro_short }} build-dpkg:${{ matrix.distro_short }} /build.sh -I.git -Iwin32_utils --unsigned-source --unsigned-changes

      - name: debug-show-files
        run: |
          echo "Files named *.changes"
          pwd
          find adaptit/ | grep "\.changes" || true
          find adaptit/artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          # Skip dpkg created source *.tar.gz. Release already has it.
          files: |
            adaptit/ChangeLog
            adaptit/artifacts/*.dsc
            adaptit/artifacts/*.deb
            adaptit/artifacts/*.changes
