on:
  push:
    tags:
      - "adaptit-*"
#    branches:
#      - release

jobs:
  build-dpkg:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [focal, bionic]
    steps:
      - uses: actions/checkout@v2

      - name: autogen.sh
        run: |
          echo "Running autogen.sh in bin/linux"
          cd bin/linux && ./autogen.sh

      - id: build-focal
        uses: kanaka/build-dpkg@focal-v1
        if: ${{ matrix.distro == "focal" }}
        with: {LOCAL: focal, args: --unsigned-source --unsigned-changes}

      - id: build-bionic
        uses: kanaka/build-dpkg@bionic-v1
        if: ${{ matrix.distro == "bionic" }}
        with: {LOCAL: bionic, args: --unsigned-source --unsigned-changes}

      - name: debug-show-files
        run: |
          echo "Files named *.changes"
          pwd
          find . | grep "\.changes" || true
          find artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ChangeLog
            artifacts/adaptit_*
            artifacts/adaptit-*
