on:
  push:
    branches:
      - release

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: update build file timestamps
        run: |
          echo "Updating build file timestamps"
          touch bin/linux/*

      - uses: nylas/build-dpkg-buster@v1
        id: build
        with:
          args: --unsigned-source --unsigned-changes

      - uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.build.outputs.filename }}
          path: ${{ steps.build.outputs.filename }}
