on:
  push:
    tags:
      - "adaptit-*"
#    branches:
#      - release

jobs:
  build-focal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: autogen.sh
        run: |
          echo "Running autogen.sh in bin/linux"
          cd bin/linux && ./autogen.sh

      - uses: kanaka/build-dpkg-focal@v1
        id: build
        with:
          args: --unsigned-source --unsigned-changes

#      - uses: actions/upload-artifact@v3
#        with:
#          name: deb packages
#          path: adaptit-*

      - name: debug-show-files
        run: |
          echo "Files named *.changes"
          pwd
          find .. | grep "\.changes" || true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ChangeLog
            ../artifacts/adaptit_*
            ../artifacts/adaptit-*
